import React from "react";
export const metadata = {
  title: "Home | About Page",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div>
      <h1 className="text-center">About page</h1>
    </div>
  );
};

export default Page;
